//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jannbo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int Car_Id { get; set; }
        public string Car_Type { get; set; }
        public string Car_Name { get; set; }
        public string Car_Plate { get; set; }
    }
}
